### PR TITLE
Small improvement for "isNode" method signature

### PR DESCRIPTION
**Pull request by satelllte**
## About

Update `isNode` utility signature to return [type predicate](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) instead of `boolean` so the consumers can use the power of TS type narrowing.

## Question

I think it's also worth to replace the input type from `any` to `unknown` or even to `number | NodeRepr_t` so consumers won't be able to use this for something else than numbers or Elementary nodes. @nick-thompson does any of it makes sense? If yes, I can update the code for this as well in this pull request.

Thanks! 🙏

### CODE REVIEW

**Comment by nick-thompson** [comment]
Thank you @satelllte, and apologies for the delay! Yes, great, I'm happy to take this change. Can you update it to merge against the `develop` branch instead of `main`?

> I think it's also worth to replace the input type from any to unknown or even to number | NodeRepr_t so consumers won't be able to use this for something else than numbers or Elementary nodes.

My thought in choosing `any` was that `isNode` can generically tell you whether the thing you passed is a `NodeRepr_t`. You don't need to have any information about the thing you're passing in; we'll look at it and tell you. If we changed the type signature to `isNode(x: number | NodeRepr_t)` that would imply that the caller already does have some information about the argument, so maybe they don't really need to check `isNode`. So, that said, I think keeping it generic makes sense but admittedly I don't know very well the tradeoffs between using `any` vs `unknown` here. Would you mind explaining?

**Comment by satelllte** [comment]
Hey @nick-thompson 👋🏻 

---

> Can you update it to merge against the develop branch instead of main?

Yes, sure!

---

> If we changed the type signature to `isNode(x: number | NodeRepr_t)` that would imply that the caller already does have some information about the argument, so maybe they don't really need to check `isNode`.

I see, yes, that makes sense. I wasn't just 100% sure about it before this explanation.

---

> but admittedly I don't know very well the tradeoffs between using `any` vs `unknown` here. Would you mind explaining?

Sure! 

First of all, `any` isn't recommended to be used at all, because it basically "turns off" TypeScript checks for it and behaves the same way as in vanilla JavaScript. So it should be used only in the process of migrating a JavaScript project to TypeScript.

So when you need to accept anything, `unknown` is designed for this particular case semantically. TypeScript compiler doesn't allow you to do anything with it until the type is figured out.

Also, for some real use case scenario (very similar to this one we have here), you can take a look at [Zod's parse()](https://github.com/colinhacks/zod/blob/cfbc7b3f6714ced250dd4053822faf472bf1828e/src/types.ts#L224-L228) method signature - you can see `unknown` is used there. Zod is just a TypeScript-based schema validation library.

**Comment by satelllte** [comment]
@nick-thompson but unfortunately, if I'm changing `any` to `unknown` there's the TypeScript error:

```
Argument of type 'unknown' is not assignable to parameter of type '{ readonly symbol: unknown; }'.
Property 'symbol' is missing in type '{}' but required in type '{ readonly symbol: unknown; }'
```

It happens because `unknown` can't be accepted in this underlying signature: 

https://github.com/elemaudio/elementary/blob/2123bc490e7c82b267de1cd1f8cb106d2ecaf27b/js/packages/core/src/Reconciler.gen.ts#L86

Is it possible to change it in this `Reconciler.gen.ts` file? I'm not familiar on how it generates

**Comment by nick-thompson** [comment]
Aha! Ok excellent, thank you for the explanation. Yea that `Reconciler.gen.ts` file is generated from ReScript, the source file is `Reconciler.res`. I just briefly looked for a way to type that `isNode` function correctly in ReScript but I don't see the kind of interop with `unknown` that we're looking for. Could we type the `isNode` function in `nodeUtils.ts` accepting `unknown` but then cast to `any` on the internal call to the rescript-generated isNode?

**Comment by satelllte** [comment]
> Could we type the `isNode` function in `nodeUtils.ts` accepting `unknown` but then cast to `any` on the internal call to the rescript-generated isNode?

As far as I saw, we can do it with `@ts-expect-error`, so it'll be ignored internally

**Comment by satelllte** [comment]
@nick-thompson I've just pushed the change, check it out

**Comment by nick-thompson** [comment]
Excellent, thank you! Merged in [e64cf1b](https://github.com/elemaudio/elementary/commit/e64cf1b7581c706d1f7b253f17f5768ee7a8f458) (I rebased and squashed at the same time; it seems github doesn't understand that that commit resolves this PR so I will just close manually)

**Comment by nick-thompson** [comment]
Ah shoot, I'm sorry that also didn't correctly reflect that the commit came from you in the git log, I wonder if there's a way I can fix that without a force-push

**Comment by nick-thompson** [comment]
Ok I reverted my merge commit and re-applied it correctly attributing you. Sorry about that, but glad I can correctly mark you as a contributor this way :) Thanks again

**Pull request closed without merging**
